apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: cybericebox
spec:
  selector:
    app: wireguard
  ports:
    - protocol: TCP
      name: grpc
      port: 5454
      targetPort: 5454
    - protocol: UDP
      name: vpn
      port: 51820
      targetPort: 51820
  