// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/sqlc-dev/pqtype"
)

type VpnClient struct {
	ID             uuid.UUID    `json:"id"`
	IpAddress      pqtype.Inet  `json:"ip_address"`
	PublicKey      string       `json:"public_key"`
	PrivateKey     string       `json:"private_key"`
	LaboratoryCidr pqtype.Inet  `json:"laboratory_cidr"`
	Banned         bool         `json:"banned"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	CreatedAt      time.Time    `json:"created_at"`
}
