// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"net/netip"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type VpnClient struct {
	UserID         uuid.UUID          `json:"user_id"`
	GroupID        uuid.UUID          `json:"group_id"`
	IpAddress      netip.Prefix       `json:"ip_address"`
	PublicKey      string             `json:"public_key"`
	PrivateKey     string             `json:"private_key"`
	LaboratoryCidr netip.Prefix       `json:"laboratory_cidr"`
	Banned         bool               `json:"banned"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedAt      time.Time          `json:"created_at"`
}
