// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateVpnClient(ctx context.Context, arg CreateVpnClientParams) error
	DeleteVPNClients(ctx context.Context, arg DeleteVPNClientsParams) (int64, error)
	GetPlatformSettings(ctx context.Context, key string) ([]byte, error)
	GetVPNClients(ctx context.Context) ([]VpnClient, error)
	UpdatePlatformSettings(ctx context.Context, arg UpdatePlatformSettingsParams) (int64, error)
	UpdateVPNClientsBanStatus(ctx context.Context, arg UpdateVPNClientsBanStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
