// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vpn_clients.sql

package postgres

import (
	"context"
	"net/netip"

	"github.com/gofrs/uuid"
)

const createVpnClient = `-- name: CreateVpnClient :exec
insert into vpn_clients (user_id, group_id, ip_address, public_key, private_key, laboratory_cidr)
values ($1, $2, $3, $4, $5, $6)
`

type CreateVpnClientParams struct {
	UserID         uuid.UUID    `json:"user_id"`
	GroupID        uuid.UUID    `json:"group_id"`
	IpAddress      netip.Prefix `json:"ip_address"`
	PublicKey      string       `json:"public_key"`
	PrivateKey     string       `json:"private_key"`
	LaboratoryCidr netip.Prefix `json:"laboratory_cidr"`
}

func (q *Queries) CreateVpnClient(ctx context.Context, arg CreateVpnClientParams) error {
	_, err := q.db.Exec(ctx, createVpnClient,
		arg.UserID,
		arg.GroupID,
		arg.IpAddress,
		arg.PublicKey,
		arg.PrivateKey,
		arg.LaboratoryCidr,
	)
	return err
}

const deleteVPNClients = `-- name: DeleteVPNClients :execrows
delete
from vpn_clients
where user_id = coalesce($1, user_id)
  and group_id = coalesce($2, group_id)
`

type DeleteVPNClientsParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

func (q *Queries) DeleteVPNClients(ctx context.Context, arg DeleteVPNClientsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVPNClients, arg.UserID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVPNClients = `-- name: GetVPNClients :many
select user_id,
       group_id,
       ip_address,
       public_key,
       private_key,
       laboratory_cidr,
       banned,
       updated_at,
       created_at
from vpn_clients
`

func (q *Queries) GetVPNClients(ctx context.Context) ([]VpnClient, error) {
	rows, err := q.db.Query(ctx, getVPNClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VpnClient{}
	for rows.Next() {
		var i VpnClient
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.IpAddress,
			&i.PublicKey,
			&i.PrivateKey,
			&i.LaboratoryCidr,
			&i.Banned,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVPNClientsBanStatus = `-- name: UpdateVPNClientsBanStatus :execrows
update vpn_clients
set banned     = $1,
    updated_at = now()
where user_id = coalesce($2, user_id)
  and group_id = coalesce($3, group_id)
`

type UpdateVPNClientsBanStatusParams struct {
	Banned  bool          `json:"banned"`
	UserID  uuid.NullUUID `json:"user_id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

func (q *Queries) UpdateVPNClientsBanStatus(ctx context.Context, arg UpdateVPNClientsBanStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVPNClientsBanStatus, arg.Banned, arg.UserID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
